module.exports.titles = ['DELINQUENT TAX CROSS REFERENCE LISTING',
'PENALTY/INTEREST DATE 08/31/23', 'OWNER NAME', 'TAX', 'YEAR', 'BK/', 'PG', 'TAX SALE #/',
'CYCLE', 'PRINCIPAL', 'AMOUNT DUE', 'INTEREST', 'DUE', '10% TAX ', 'PENALTY',
'FIFA', 'CHARGE', 'OTHER', 'TOTAL AMT','DUE', 'HS', 'TAX DISTRICT:',
'GRAND TOTAL DUE', 'Page', 'S', 'A', 'F', 'CODE:', 'DO', 'DUE DATE:', 'STATE']

module.exports.tax_districts = {
    '04': 'UNINCORPORATED',
    '61': 'ATLANTA',
    '44': 'DORAVILLE',
    '44A': 'DORAVLLE ANX',
    '50': 'DUNWOODY',
    '80': 'STONECREST',
    '90': 'TUCKER',
    '24': 'CHAMBLEE',
    '24A': 'CHAMBLEE ANX',
    'S11': 'METRO SOUTH CID',
    '20': 'BROOKHAVEN',
    '20A': 'BROOKHAVEN ANX',
    '20B': 'BROOKHAVEN ANX B',
    '92': 'DECATUR',
    '92A': 'DECATUR ANX',
    '14': 'AVONDALE EST',
    '14A': 'AVDL EST ANX',
    '34A': 'CLARKSTN ANX',
    '34': 'CLARKSTON',
    '54': 'LITHONIA',
    '74': 'PINE LAKE',
    '74A': 'PINE LK ANX',
    '84': 'STONE MTN',
    '84A': 'STN MTN ANX',
    '80': 'STONECREST',
    '61E': 'ATL EMORY ANX',
    'S2': 'PCCID DNWDY',
    'TDRV1': 'DORAVILLE CITYTAD',
    'S17': 'CHAMBLEE DORAVILLE CID CA',
    'S3S': 'PCCID BROOK SSD',
    'S10T': 'ASSEMBLY CID',
    'S16': 'CHAMBLEE DORAVILLE CID C',
    '20S': 'BROOKHAVEN SSD',
    'S4': 'STONE MOUNTAIN CID',
    'S5': 'TUCKER-NORTHLAKE CID',
    'S4': 'TUCKER SUMMIT CID',
    'S6': 'EAST METRO CID',
    'S15': 'EAST METRO STCST',
    '20A': 'BROOKHAVEN ANX B',
    'TAD3': 'BRIAR20 ANX SSD',
    'TSM1': 'STMTN CTYTAD',
    'TAD#2': 'AVN/04',
    'TDEC1': 'DECATUR CITY TAD',
    'TAV1': 'AVDL CITYTAD',
    'TAD#1': 'KEN/04',
    'T104': 'TAD1 KEN 04',
    '61A': 'ATLANTA ANX',
    'S3S':'PCCID BROOK SSD',
}